---
deployment:
  tasks:
    - /bin/mkdir -p /home/pmsbdcom/public_html /home/pmsbdcom/laravel
    - export DEPLOYPATH=/home/pmsbdcom/public_html/
    - /bin/cp -a public/. $DEPLOYPATH
    - export DEPLOYPATH=/home/pmsbdcom/laravel/
    - /bin/cp -a laravel/. $DEPLOYPATH
